### ISSUE TITLE
Idea: Re-export ruma-identifiers and ruma-events from this crate

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-common#2]
This would mean ruma-common is no longer just an internal crate, but ruma-identifiers and ruma-events would no longer have to be imported separately into projects using ruma-*-api.

On top of this, we could potentially even move the two crates into this repository.

**Comment by jplatte** [comment]
So I'm a bit uncertain still.. People were generally positive about this chance in the ruma chat, but it feels a bit weird to use this crate only to define things which are used in multiple api crates, not things used in ruma-events & ruma-client-api (of which there's quite a few). If this crate is going to re-export ruma-events, then we can't move things from ruma-events that would make much more sense if exposed from this crate over here because that would create a circular dependency. It seems like to solve that, we need yet another crate which will do the re-exporting (of ruma-identifiers, ruma-events, and everything defined here). But what do we then call that crate, and will this one keep its current name? I don't have good answers to these questions right now.

Ideas / opinions? @poljar @timokoesters @iinuwa

**Comment by timokoesters** [comment]
Is it a good idea to merge these crates into one instead of reexporting?

**Comment by iinuwa** [comment]
So it seems we have two goals:
1. Provide a place for shared types for code reuse library producers
2. Simplify the dependency graph for consumers to configure.

The former is needed not to have to repeat code in two places, allowing for divergence in their definitions. It also helps consumers in that types that have the same name are actually the same type, and can be used as such.

The latter is helpful since consumers currently have to track which versions of ruma-*-api are compatible with ruma-events and ruma-identifiers (and serde? don't know about that one). If I may stop outside the box a little, I think a best case scenario would be if consumers could specify something like `ruma-lib = { version = "1.0.0", features = ["client", "federation"] }` to get the client and federation endpoint types along with the relevant identifiers and events.

(I don't know if that's possible, just throwing ideas out there. This may also not be as relevant if/when Ruma libraries hit 1.0, since there would be less churn from breaking changes anyway.)

I digress. As to your actual question, I think something like ruma-common is a good name for an internal crate. I think ruma-core or ruma-base are candidates for the public crates.

**Comment by jplatte** [comment]
> If I may stop outside the box a little, I think a best case scenario would be if consumers could specify something like `ruma-lib = { version = "1.0.0", features = ["client", "federation"] }` to get the client and federation endpoint types along with the relevant identifiers and events.

I love this idea! I'm also very tempted to (re)use the crate name `ruma` for this ([which we have reserved on crates.io](https://crates.io/crates/ruma)). The only thing I'm not sure about is how the `ruma-client` crate would fit into this.

**Comment by iinuwa** [comment]
Yeah, I thought about that too. I think that having `ruma-lib` and `ruma-client` might help disambiguate the two. If we reuse `ruma` for the library, then using `ruma = {... features = ["client"] }` would be confusing, I think.

**Comment by jplatte** [comment]
Since homeservers also need to make requests to other homeservers for federation, maybe we should just also re-export that via a feature from `ruma`?

Then we'd have

```toml
[dependencies.ruma]
version = "0.1"
features = ["client", "client-api", "federation-api", "appservice-api", "signatures"]
```

for a homeserver, `features = ["client", "client-api"]` for a client, `features = ["client", "client-api", "appservice-api"]` for an appservice and so on. Things like fractal would just enable no features at all since `ruma` would always expose the shared types, and such such also `ruma-identifiers` (which the shared types depend on). Some very special applications might explicitly enable the `events` feature, but normally you wouldn't have to because the various api features would activate it implicitly.

The module structure would then be

```rust
ruma::{
    api::{appservice, client, federation},
    client,
    // this may be flattened into the outer namespace actually, so we'd instead
    // have modules like `push` for push notifications
    common,
    events,
    identifiers,
    signatures,
}
```

(or maybe `api` would not be a submodule, and instead there's be `ruma::appservice_api`, `ruma::client_api` and `ruma::federation_api`)

**Comment by jplatte** [comment]
Alright, it has been decided! The [ruma crate](https://github.com/ruma/ruma) is going to re-export everything else, though probably not `ruma_client` *initially*, and not necessarily all future crates (`js_int` which I have been thinking about moving into the ruma organization, would not be re-exported for example).
